import { z } from 'zod';
import type { GateName, InvisibleDBClient, MigrationAction } from './client.js';
export const provisionSchema = { name: z.string().min(1).max(63), domain: z.string().optional(), plan: z.enum(['seat','dev']).optional() }; export type ProvisionArgs = z.infer<z.ZodObject<typeof provisionSchema>>;
export const keysSchema = { instance: z.string().min(1) }; export type KeysArgs = z.infer<z.ZodObject<typeof keysSchema>>;
export const querySchema = { instance: z.string().min(1), collection: z.string().min(1), filter: z.string().optional(), page: z.number().int().positive().optional(), perPage: z.number().int().positive().max(200).optional() }; export type QueryArgs = z.infer<z.ZodObject<typeof querySchema>>;
const gateNames = ['typecheck','unit-tests','integration-tests','security','migration-safety','production-readiness'] as const; export const gateCheckSchema = { instance: z.string().min(1), gate: z.enum(gateNames) }; export type GateCheckArgs = z.infer<z.ZodObject<typeof gateCheckSchema>>;
const manifest = z.record(z.unknown()); const migrationId = z.string().min(1); const instance = z.string().min(1);
function text(payload: unknown) { return { content: [{ type: 'text' as const, text: JSON.stringify(payload, null, 2) }] }; }
async function migrate(client: InvisibleDBClient, instanceName: string, action: MigrationAction, payload: Record<string, unknown> = {}) { return text(await client.migration(instanceName, action, payload)); }
export async function handleProvision(client: InvisibleDBClient, args: ProvisionArgs) { const inst = await client.provision({ name: args.name, domain: args.domain, plan: args.plan }); return text({ ...inst, note: inst.status === 'provisioning' ? 'Poll idb_list until ready; provisioning is not success evidence.' : undefined }); }
export async function handleList(client: InvisibleDBClient) { const instances = await client.list(); return text({ instances, count: instances.length }); }
export async function handleKeys(client: InvisibleDBClient, args: KeysArgs) { return text(await client.keys(args.instance)); }
export async function handleQuery(client: InvisibleDBClient, args: QueryArgs) { return text(await client.query(args.instance, args.collection, args.filter, { page: args.page, perPage: args.perPage })); }
export async function handleGateCheck(client: InvisibleDBClient, args: GateCheckArgs) { const result = await client.gateCheck(args.instance, args.gate as GateName); return text({ ...result, interpretation: result.state === 'VERIFIED' ? `Gate ${args.gate} passed.` : `Gate ${args.gate} is ${result.state}; treat as not-passed.` }); }
export async function handleStatus(client: InvisibleDBClient) { return text(await client.status()); }
const POSTGRES_DISCOVERY = {
  instructions: ['Run these read-only queries through the Lovable/Supabase/Postgres source connector.','Assemble MigrationManifest v1.0 without inventing missing facts.','Include auth.users only when authorized; set auth.userTable.','If storage exists, include bucket object counts and later stage object metadata as {source_key:"bucket/path",bucket,path,metadata}.','Run idb_migration_plan before mutating the destination.'],
  sql: {
    relations: `select n.nspname as schema_name,c.relname as relation_name,case c.relkind when 'r' then 'table' when 'v' then 'view' when 'm' then 'materialized_view' end as kind,coalesce(s.n_live_tup,0)::bigint as row_count from pg_class c join pg_namespace n on n.oid=c.relnamespace left join pg_stat_user_tables s on s.relid=c.oid where c.relkind in ('r','v','m') and n.nspname not in ('pg_catalog','information_schema') order by 1,2;`,
    columns: `select table_schema,table_name,column_name,data_type,udt_name,is_nullable,column_default,ordinal_position from information_schema.columns where table_schema not in ('pg_catalog','information_schema') order by table_schema,table_name,ordinal_position;`,
    primaryKeys: `select tc.table_schema,tc.table_name,kcu.column_name,kcu.ordinal_position from information_schema.table_constraints tc join information_schema.key_column_usage kcu on tc.constraint_name=kcu.constraint_name and tc.table_schema=kcu.table_schema where tc.constraint_type='PRIMARY KEY' order by 1,2,4;`,
    foreignKeys: `select tc.table_schema,tc.table_name,kcu.column_name,ccu.table_schema as foreign_table_schema,ccu.table_name as foreign_table_name,ccu.column_name as foreign_column_name,rc.delete_rule from information_schema.table_constraints tc join information_schema.key_column_usage kcu on tc.constraint_name=kcu.constraint_name and tc.table_schema=kcu.table_schema join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema join information_schema.referential_constraints rc on rc.constraint_name=tc.constraint_name and rc.constraint_schema=tc.table_schema where tc.constraint_type='FOREIGN KEY' order by 1,2;`,
    indexes: `select schemaname,tablename,indexname,indexdef from pg_indexes where schemaname not in ('pg_catalog','information_schema') order by 1,2,3;`,
    policies: `select schemaname,tablename,policyname,cmd,roles,qual,with_check from pg_policies order by schemaname,tablename,policyname;`,
    triggers: `select event_object_schema,event_object_table,trigger_name,action_statement,action_timing,event_manipulation from information_schema.triggers where trigger_schema not in ('pg_catalog','information_schema') order by 1,2,3;`,
    extensions: `select extname from pg_extension order by extname;`,
    functions: `select n.nspname as schema_name,p.proname as function_name,l.lanname as language from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname not in ('pg_catalog','information_schema') order by 1,2;`,
    storageBuckets: `select id,name,public,file_size_limit,allowed_mime_types from storage.buckets order by name;`,
    storageCounts: `select bucket_id,count(*)::bigint as objects_count,coalesce(sum((metadata->>'size')::bigint),0)::bigint as bytes from storage.objects group by bucket_id order by bucket_id;`
  },
  manifestShape: { version: '1.0', source: { provider: 'lovable-cloud', engine: 'postgres', projectId: '<source project id>', capturedAt: '<ISO timestamp>' }, tables: [{ name: 'public.example', kind: 'table', rowCount: 0, primaryKey: ['id'], columns: [{ name: 'id', sourceType: 'uuid', nullable: false }], foreignKeys: [], indexes: [], policies: [], triggers: [] }], auth: { provider: 'supabase-auth', usersCount: 0, passwordHashExportable: false, userTable: 'auth.users' }, storage: { buckets: [] }, functions: [], realtime: [], extensions: [], metadata: {} }
};
export interface ToolDef { name: string; description: string; schema: Record<string, z.ZodTypeAny>; handler: (client: InvisibleDBClient, args: never) => Promise<unknown> }
export const tools: ToolDef[] = [
  { name:'idb_provision',description:'Provision a new InvisibleDB hosted instance.',schema:provisionSchema,handler:handleProvision as ToolDef['handler'] },{ name:'idb_list',description:'List InvisibleDB instances.',schema:{},handler:handleList as ToolDef['handler'] },{ name:'idb_keys',description:'Get destination instance secret key/snippets. Do not log.',schema:keysSchema,handler:handleKeys as ToolDef['handler'] },{ name:'idb_query',description:'Query a destination collection.',schema:querySchema,handler:handleQuery as ToolDef['handler'] },{ name:'idb_gate_check',description:'Check a lifecycle gate. Only VERIFIED passes.',schema:gateCheckSchema,handler:handleGateCheck as ToolDef['handler'] },{ name:'idb_status',description:'Control-plane health.',schema:{},handler:handleStatus as ToolDef['handler'] },
  { name:'idb_migration_manifest_spec',description:'Get MigrationManifest v1.0 plus read-only Lovable/Supabase/Postgres discovery SQL.',schema:{},handler:(async()=>text(POSTGRES_DISCOVERY)) as ToolDef['handler'] },
  { name:'idb_migration_plan',description:'Compile a read-only compatibility plan.',schema:{instance,manifest},handler:(async(c:InvisibleDBClient,a:any)=>migrate(c,a.instance,'plan',{manifest:a.manifest})) as ToolDef['handler'] },
  { name:'idb_migration_create',description:'Persist a reviewed migration.',schema:{instance,manifest},handler:(async(c:InvisibleDBClient,a:any)=>migrate(c,a.instance,'create',{manifest:a.manifest})) as ToolDef['handler'] },
  { name:'idb_migration_start',description:'Queue the pre-migration snapshot.',schema:{instance,migrationId},handler:(async(c:InvisibleDBClient,a:any)=>migrate(c,a.instance,'start',{migrationId:a.migrationId})) as ToolDef['handler'] },
  { name:'idb_migration_prepare',description:'Create collections, relations, and compiled indexes after snapshot.',schema:{instance,migrationId},handler:(async(c:InvisibleDBClient,a:any)=>migrate(c,a.instance,'prepare',{migrationId:a.migrationId})) as ToolDef['handler'] },
  { name:'idb_migration_batch',description:'Import an idempotent 1-500 row data batch.',schema:{instance,migrationId,batchKey:z.string().regex(/^[A-Za-z0-9_-]+$/),collection:z.string().min(1),records:z.array(z.record(z.unknown())).min(1).max(500),checksum:z.string().optional()},handler:(async(c:InvisibleDBClient,a:any)=>migrate(c,a.instance,'batch',{migrationId:a.migrationId,batchKey:a.batchKey,collection:a.collection,records:a.records,checksum:a.checksum})) as ToolDef['handler'] },
  { name:'idb_migration_auth_batch',description:'Import 1-500 auth identities with explicit reset semantics.',schema:{instance,migrationId,batchKey:z.string().regex(/^[A-Za-z0-9_-]+$/),collection:z.string().optional(),users:z.array(z.record(z.unknown())).min(1).max(500)},handler:(async(c:InvisibleDBClient,a:any)=>migrate(c,a.instance,'auth_batch',{migrationId:a.migrationId,batchKey:a.batchKey,collection:a.collection,users:a.users})) as ToolDef['handler'] },
  { name:'idb_migration_file',description:'Transfer one signed-URL storage object source→InvisibleDB; bytes never enter model context.',schema:{instance,migrationId,collection:z.string().min(1),sourceRecordId:z.string().min(1),field:z.string().min(1),filename:z.string().min(1),sourceUrl:z.string().url(),expectedSha256:z.string().optional()},handler:(async(c:InvisibleDBClient,a:any)=>migrate(c,a.instance,'file',{migrationId:a.migrationId,collection:a.collection,sourceRecordId:a.sourceRecordId,field:a.field,filename:a.filename,sourceUrl:a.sourceUrl,expectedSha256:a.expectedSha256})) as ToolDef['handler'] },
  { name:'idb_migration_resolve',description:'Resolve one active cutover blocker only after the agent supplies concrete evidence of the rewrite/fix.',schema:{instance,migrationId,blocker:z.string().min(1),evidence:z.string().min(1).max(2000)},handler:(async(c:InvisibleDBClient,a:any)=>migrate(c,a.instance,'resolve',{migrationId:a.migrationId,blocker:a.blocker,evidence:a.evidence})) as ToolDef['handler'] },
  { name:'idb_migration_verify',description:'Verify counts, batches, and unresolved blockers.',schema:{instance,migrationId},handler:(async(c:InvisibleDBClient,a:any)=>migrate(c,a.instance,'verify',{migrationId:a.migrationId})) as ToolDef['handler'] },
  { name:'idb_migration_cutover',description:'Generate cutover configuration only for VERIFIED migrations.',schema:{instance,migrationId},handler:(async(c:InvisibleDBClient,a:any)=>migrate(c,a.instance,'cutover',{migrationId:a.migrationId})) as ToolDef['handler'] },
  { name:'idb_migration_rollback',description:'Queue restore of a pre-migration backup.',schema:{instance,migrationId,backup:z.string().min(1)},handler:(async(c:InvisibleDBClient,a:any)=>migrate(c,a.instance,'rollback',{migrationId:a.migrationId,backup:a.backup})) as ToolDef['handler'] },
  { name:'idb_migration_status',description:'Read one or recent migrations.',schema:{instance,migrationId:z.string().optional()},handler:(async(c:InvisibleDBClient,a:any)=>text(await c.migrationStatus(a.instance,a.migrationId))) as ToolDef['handler'] },
];
