'use client';
import { useEffect, useState } from 'react';

type Job = { id: string; status: string; sourceProvider: string; createdAt: string; plan?: any; verification?: any; progress?: any; error?: string | null };

export default function MigrationManager({ slug }: { slug: string }) {
  const [manifest, setManifest] = useState(''); const [plan, setPlan] = useState<any>(null); const [jobs, setJobs] = useState<Job[]>([]); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const endpoint = `/api/projects/${encodeURIComponent(slug)}/migrations`;
  const load = async () => { const res = await fetch(endpoint, { cache: 'no-store' }); if (res.ok) setJobs(await res.json()); };
  useEffect(() => { void load(); }, [slug]);
  const post = async (body: any) => { setError(''); const res = await fetch(endpoint, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || 'Migration request failed'); return data; };
  const analyze = async () => { try { setBusy('plan'); const parsed = JSON.parse(manifest); setPlan(await post({ action: 'plan', manifest: parsed })); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } };
  const create = async () => { try { setBusy('create'); const parsed = JSON.parse(manifest); await post({ action: 'create', manifest: parsed }); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } };
  const action = async (name: string, migrationId: string) => { try { setBusy(`${name}:${migrationId}`); await post({ action: name, migrationId }); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } };
  return <div>
    <div style={{ padding: 18, border: '1px solid #292929', borderRadius: 12, background: '#0f0f0f' }}><h2 style={{ marginTop: 0 }}>AI migration manifest</h2><p style={{ color: '#888', lineHeight: 1.65 }}>For Lovable: connect the Lovable MCP and InvisibleDB MCP to the same agent, call <code>idb_migration_manifest_spec</code>, and let the agent populate this automatically. You can also paste a MigrationManifest v1.0 here.</p><textarea value={manifest} onChange={(e) => setManifest(e.target.value)} placeholder='{"version":"1.0","source":{"provider":"lovable-cloud","engine":"postgres","capturedAt":"..."},"tables":[]}' style={{ width: '100%', minHeight: 210, padding: 12, fontFamily: 'monospace', background: '#080808', color: '#eee', border: '1px solid #333', borderRadius: 8 }} /><div style={{ display: 'flex', gap: 10, marginTop: 12 }}><button className="btn" disabled={!manifest || !!busy} onClick={analyze}>{busy === 'plan' ? 'Analyzing…' : 'Analyze'}</button><button className="btn primary" disabled={!manifest || !!busy} onClick={create}>{busy === 'create' ? 'Creating…' : 'Create migration'}</button></div>{error ? <p style={{ color: '#ff6b6b' }}>{error}</p> : null}</div>
    {plan ? <div style={{ marginTop: 18, padding: 18, border: '1px solid #333', borderRadius: 12 }}><h3 style={{ marginTop: 0 }}>Compatibility {plan.compatibility}%</h3><p><strong>{plan.collections?.length ?? 0}</strong> collections · <strong>{plan.warnings?.length ?? 0}</strong> warnings · <strong>{plan.blockers?.length ?? 0}</strong> cutover blockers</p>{plan.blockers?.length ? <div><strong style={{ color: '#ff8a65' }}>Must resolve before cutover</strong><ul>{plan.blockers.map((x: string) => <li key={x}>{x}</li>)}</ul></div> : <p style={{ color: '#65d38e' }}>No cutover blockers detected.</p>}{plan.warnings?.length ? <details><summary>Warnings</summary><ul>{plan.warnings.map((x: string) => <li key={x}>{x}</li>)}</ul></details> : null}</div> : null}
    <h2 style={{ marginTop: 32 }}>Migration jobs</h2>{jobs.length === 0 ? <p style={{ color: '#777' }}>No migrations yet.</p> : jobs.map((job) => <div key={job.id} style={{ padding: 16, border: '1px solid #252525', borderRadius: 10, marginBottom: 12 }}><div style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}><strong>{job.sourceProvider}</strong><span className="badge">{job.status.toUpperCase()}</span><code style={{ color: '#777' }}>{job.id}</code></div>{job.error ? <p style={{ color: '#ff6b6b' }}>{job.error}</p> : null}{job.verification ? <pre style={{ whiteSpace: 'pre-wrap', color: '#aaa', fontSize: 12 }}>{JSON.stringify(job.verification, null, 2)}</pre> : null}<div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 12 }}>{job.status === 'planned' || job.status === 'failed' ? <button className="btn" disabled={!!busy} onClick={() => action('start', job.id)}>Snapshot & start</button> : null}{job.status === 'snapshotting' ? <button className="btn" disabled={!!busy} onClick={() => action('prepare', job.id)}>Prepare schema</button> : null}{['schema_ready','importing','staged'].includes(job.status) ? <button className="btn" disabled={!!busy} onClick={() => action('verify', job.id)}>Verify</button> : null}{job.status === 'verified' ? <button className="btn primary" disabled={!!busy} onClick={() => action('cutover', job.id)}>Generate cutover</button> : null}</div></div>)}
  </div>;
}
