export const POSTGRES_DISCOVERY = {
  instructions: [
    'Run these read-only queries through the Lovable/Supabase/Postgres source connector.',
    'relation_inventory.estimated_rows is discovery-only. Never copy an estimate into manifest.tables[].rowCount.',
    'Run exact_count_statements, then execute every returned count SQL. Only those exact COUNT(*) values belong in manifest.tables[].rowCount.',
    'Assemble MigrationManifest v1.0 without inventing missing schema facts.',
    'Include auth.users only when the source connector is authorized to read it; set auth.userTable accordingly.',
    'For storage, include exact object counts for every bucket. Missing counts keep verification PARTIAL.',
    'Run idb_migration_plan before any destination mutation.',
  ],
  sql: {
    relation_inventory: `select n.nspname as schema_name,c.relname as relation_name,case c.relkind when 'r' then 'table' when 'v' then 'view' when 'm' then 'materialized_view' end as kind,coalesce(s.n_live_tup,0)::bigint as estimated_rows from pg_class c join pg_namespace n on n.oid=c.relnamespace left join pg_stat_user_tables s on s.relid=c.oid where c.relkind in ('r','v','m') and n.nspname not in ('pg_catalog','information_schema') order by 1,2;`,
    exact_count_statements: `select format('select %L as relation_name, count(*)::bigint as row_count from %I.%I;',n.nspname||'.'||c.relname,n.nspname,c.relname) as sql from pg_class c join pg_namespace n on n.oid=c.relnamespace where c.relkind in ('r','m') and n.nspname not in ('pg_catalog','information_schema') order by n.nspname,c.relname;`,
    columns: `select table_schema,table_name,column_name,data_type,udt_name,is_nullable,column_default,ordinal_position from information_schema.columns where table_schema not in ('pg_catalog','information_schema') order by table_schema,table_name,ordinal_position;`,
    primary_keys: `select tc.table_schema,tc.table_name,kcu.column_name,kcu.ordinal_position from information_schema.table_constraints tc join information_schema.key_column_usage kcu on tc.constraint_name=kcu.constraint_name and tc.table_schema=kcu.table_schema where tc.constraint_type='PRIMARY KEY' order by 1,2,4;`,
    foreign_keys: `select tc.table_schema,tc.table_name,kcu.column_name,ccu.table_schema as foreign_table_schema,ccu.table_name as foreign_table_name,ccu.column_name as foreign_column_name,rc.delete_rule from information_schema.table_constraints tc join information_schema.key_column_usage kcu on tc.constraint_name=kcu.constraint_name and tc.table_schema=kcu.table_schema join information_schema.constraint_column_usage ccu on ccu.constraint_name=tc.constraint_name and ccu.table_schema=tc.table_schema join information_schema.referential_constraints rc on rc.constraint_name=tc.constraint_name and rc.constraint_schema=tc.table_schema where tc.constraint_type='FOREIGN KEY' order by 1,2;`,
    indexes: `select ns.nspname as schema_name,t.relname as table_name,i.relname as index_name,ix.indisunique as is_unique,array_agg(a.attname order by k.ord) filter (where a.attname is not null) as columns from pg_index ix join pg_class t on t.oid=ix.indrelid join pg_class i on i.oid=ix.indexrelid join pg_namespace ns on ns.oid=t.relnamespace join lateral unnest(ix.indkey) with ordinality as k(attnum,ord) on true left join pg_attribute a on a.attrelid=t.oid and a.attnum=k.attnum where ns.nspname not in ('pg_catalog','information_schema') group by ns.nspname,t.relname,i.relname,ix.indisunique order by 1,2,3;`,
    policies: `select schemaname,tablename,policyname,cmd,roles,qual,with_check from pg_policies order by schemaname,tablename,policyname;`,
    triggers: `select event_object_schema,event_object_table,trigger_name,action_statement,action_timing,event_manipulation from information_schema.triggers where trigger_schema not in ('pg_catalog','information_schema') order by 1,2,3;`,
    extensions: `select extname from pg_extension order by extname;`,
    functions: `select n.nspname as schema_name,p.proname as function_name,l.lanname as language from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname not in ('pg_catalog','information_schema') order by 1,2;`,
    auth_users_count: `select count(*)::bigint as users_count from auth.users;`,
    storage_buckets: `select id,name,public,file_size_limit,allowed_mime_types from storage.buckets order by name;`,
    storage_counts: `select bucket_id,count(*)::bigint as objects_count,coalesce(sum(nullif(metadata->>'size','')::bigint),0)::bigint as bytes from storage.objects group by bucket_id order by bucket_id;`,
  },
  manifestShape: {
    version: '1.0',
    source: { provider: 'lovable-cloud', engine: 'postgres', projectId: '<source project id>', capturedAt: '<ISO timestamp>' },
    tables: [{ name: 'public.example', kind: 'table', rowCount: 0, primaryKey: ['id'], columns: [{ name: 'id', sourceType: 'uuid', nullable: false }], foreignKeys: [], indexes: [], policies: [], triggers: [] }],
    auth: { provider: 'supabase-auth', usersCount: 0, passwordHashExportable: false, userTable: 'auth.users' },
    storage: { buckets: [] },
    functions: [],
    realtime: [],
    extensions: [],
    metadata: {},
  },
  storageRecordShape: { source_key: 'bucket/path/to/file.ext', bucket: 'bucket', path: 'path/to/file.ext', metadata: {} },
  rules: [
    'Paginate source records and send at most 500 records per idb_migration_batch.',
    'Use stable batchKey values so retries are idempotent.',
    'Stage each storage object metadata record before calling idb_migration_file.',
    'Use signed HTTPS URLs for file transfer so bytes never enter model context.',
    'Use idb_migration_resolve only after producing concrete evidence for the active blocker.',
  ],
} as const;
