/**
 * Project store + provisioning job runner.
 *
 * Provisioning calls the REAL `createProject()` from @baas-195/adapter-cpanel.
 * For the live feed, the adapter's injectable `fetchImpl` is wrapped: every
 * raw UAPI call flips its step to running → done/failed as it completes, so
 * the UI renders each adapter step the moment it lands.
 *
 * Store is in-memory (like the connection); production needs a real DB.
 */
import { randomBytes } from 'crypto';
import {
  createProject,
  deleteProject,
  UapiClient,
  ProvisionError,
} from '@baas-195/adapter-cpanel';
import type { ProjectProvisioned, UapiConfig } from '@baas-195/adapter-cpanel';
import { getConnection } from './connection';
import { insecureFetch } from './tls';

export type StepState = 'pending' | 'running' | 'done' | 'failed' | 'skipped';

export interface ProjectStep {
  id: string;
  label: string;
  state: StepState;
  detail?: string;
  startedAt?: string;
  endedAt?: string;
}

export interface ProjectJob {
  id: string;
  name: string;
  domain: string;
  fqdn: string;
  port: number;
  status: 'provisioning' | 'ready' | 'failed';
  steps: ProjectStep[];
  result?: ProjectProvisioned;
  dbPassword?: string;
  error?: string;
  note?: string;
  seeded?: boolean;
  createdAt: string;
}

const jobs = new Map<string, ProjectJob>();

const STEP_DEFS: Array<{ id: string; label: string }> = [
  { id: 'subdomain', label: 'Create subdomain' },
  { id: 'database', label: 'Create MySQL database' },
  { id: 'dbuser', label: 'Create database user' },
  { id: 'privileges', label: 'Grant privileges' },
  { id: 'ssl', label: 'Issue SSL certificate (AutoSSL)' },
  { id: 'cron', label: 'Install watchdog cron' },
  { id: 'proxy', label: 'Write proxy rules (.htaccess)' },
];

function stepIdFor(module: string, func: string): string | null {
  if (module === 'SubDomain' && func === 'addsubdomain') return 'subdomain';
  if (module === 'Mysql' && func === 'create_database') return 'database';
  if (module === 'Mysql' && func === 'create_user') return 'dbuser';
  if (module === 'Mysql' && func === 'set_privileges_on_database') return 'privileges';
  if (module === 'SSL') return 'ssl';
  if (module === 'Cron') return 'cron';
  if (module === 'Fileman' && func === 'save_file_content') return 'proxy';
  return null;
}

function markStep(job: ProjectJob, id: string, state: StepState, detail?: string): void {
  const s = job.steps.find((x) => x.id === id);
  if (!s) return;
  s.state = state;
  if (detail) s.detail = detail;
  const now = new Date().toISOString();
  if (state === 'running' && !s.startedAt) s.startedAt = now;
  if (state === 'done' || state === 'failed' || state === 'skipped') s.endedAt = now;
}

/** fetchImpl wrapper: reports every raw UAPI call as a provisioning step. */
function trackingFetch(job: ProjectJob): typeof fetch {
  const base = insecureFetch as unknown as typeof fetch;
  return (async (input: string | URL | Request, init?: RequestInit) => {
    const raw = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
    const m = raw.match(/\/execute\/(\w+)\/(\w+)/);
    const stepId = m ? stepIdFor(m[1], m[2]) : null;
    if (stepId) markStep(job, stepId, 'running');
    try {
      const res = await base(raw, init);
      if (stepId) markStep(job, stepId, 'done');
      return res;
    } catch (e) {
      // Transport failure — the adapter retries with backoff; keep the step
      // in running so the feed shows "retrying" rather than flapping.
      if (stepId) {
        const s = job.steps.find((x) => x.id === stepId);
        if (s && s.state !== 'running') markStep(job, stepId, 'running', 'retrying…');
      }
      throw e;
    }
  }) as typeof fetch;
}

function htaccessFor(fqdn: string, port: number): string {
  const escaped = fqdn.replace(/\./g, '\\.');
  return [
    `# Generated by 1.95 BaaS control plane — ${fqdn} -> 127.0.0.1:${port}`,
    `# PocketBase API + admin UI proxied to the project binary; static files`,
    `# in the document root are served directly.`,
    `RewriteEngine On`,
    `RewriteCond %{HTTP_HOST} ^${escaped}$ [NC]`,
    `RewriteCond %{REQUEST_URI} ^/api/ [OR]`,
    `RewriteCond %{REQUEST_URI} ^/_/`,
    `RewriteRule ^(.*)$ http://127.0.0.1:${port}/$1 [P,L,QSA]`,
    ``,
  ].join('\n');
}

function allocatePort(): number {
  const used = new Set<number>();
  for (const j of jobs.values()) used.add(j.port);
  let port = 18001;
  while (used.has(port) && port < 18999) port++;
  if (port > 18999) throw new Error('port range 18001–18999 exhausted');
  return port;
}

export function listJobs(): ProjectJob[] {
  return [...jobs.values()].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export function getJob(id: string): ProjectJob | undefined {
  return jobs.get(id);
}

/** Start provisioning in the background; returns immediately with the job id. */
export function startProvisioning(name: string, domain: string): ProjectJob {
  const conn = getConnection();
  if (!conn) throw new Error('No hosting connection. Connect hosting first.');

  const id = `${name}-${Date.now().toString(36)}`;
  const port = allocatePort();
  const job: ProjectJob = {
    id,
    name,
    domain,
    fqdn: `${name}.${domain}`,
    port,
    status: 'provisioning',
    steps: STEP_DEFS.map((d) => ({ ...d, state: 'pending' as StepState })),
    createdAt: new Date().toISOString(),
  };
  jobs.set(id, job);
  // Fire and forget — the feed polls GET /api/projects/[id].
  void runProvisioning(id, conn);
  return job;
}

async function runProvisioning(id: string, conn: NonNullable<ReturnType<typeof getConnection>>): Promise<void> {
  const job = jobs.get(id);
  if (!job) return;
  const dbPassword = randomBytes(18).toString('base64').replace(/[^A-Za-z0-9]/g, 'x');
  job.dbPassword = dbPassword;

  const cfg: UapiConfig = {
    host: conn.host,
    user: conn.user,
    apiToken: conn.apiToken,
    fetchImpl: trackingFetch(job),
  };

  try {
    const provisioned = await createProject(cfg, {
      name: job.name,
      domain: job.domain,
      port: job.port,
      dbPassword,
      sslTimeoutMs: 60_000,
    });

    // Proxy rules are not part of createProject — land them as the final
    // step with the supervisor's .htaccess template, via the real adapter.
    try {
      const client = new UapiClient({ ...cfg, fetchImpl: trackingFetch(job) });
      await client.writeFile(provisioned.docRoot, '.htaccess', htaccessFor(provisioned.fqdn, provisioned.port));
    } catch (e) {
      markStep(job, 'proxy', 'failed', `proxy rules not written: ${(e as Error).message} — place .htaccess manually`);
    }

    job.result = provisioned;
    job.status = 'ready';
    for (const s of job.steps) if (s.state === 'pending') markStep(job, s.id, 'skipped', 'not needed');
  } catch (e) {
    const msg =
      e instanceof ProvisionError
        ? `Failed at step "${e.step}": ${e.cause}`
        : (e as Error).message;
    for (const s of job.steps) if (s.state === 'running') markStep(job, s.id, 'failed');
    job.status = 'failed';
    job.error = msg;
  }
}

/** Tear down via the real adapter, then drop the job from the store. */
export async function teardownProject(id: string): Promise<{ removed: string[]; errors: Array<{ step: string; error: string }> }> {
  const job = jobs.get(id);
  if (!job) throw new Error('unknown project');
  const conn = getConnection();
  if (!conn) throw new Error('No hosting connection.');
  const report = await deleteProject(
    { host: conn.host, user: conn.user, apiToken: conn.apiToken, fetchImpl: insecureFetch as unknown as typeof fetch },
    { name: job.name, domain: job.domain },
  );
  jobs.delete(id);
  return { removed: report.removed, errors: report.errors };
}

/** Seed the real demo project living on the box (vibecode → :18001). */
function seedDemo(): void {
  if (jobs.has('demo')) return;
  const done: ProjectStep[] = STEP_DEFS.map((d) => ({
    ...d,
    state: 'done' as StepState,
    startedAt: '2026-10-06T04:15:00Z',
    endedAt: '2026-10-06T04:29:00Z',
  }));
  jobs.set('demo', {
    id: 'demo',
    name: 'demo',
    domain: 'momsoilchange.com',
    fqdn: 'vibecode.momsoilchange.com',
    port: 18001,
    status: 'ready',
    steps: done,
    createdAt: '2026-10-06T04:15:00Z',
    seeded: true,
    note: 'Live demo project provisioned 2026-10-06. Public URL is served via the vibecode subdomain until the host fixes new vhosts; PocketBase runs on 127.0.0.1:18001.',
    result: {
      name: 'demo',
      fqdn: 'vibecode.momsoilchange.com',
      port: 18001,
      db: { name: 'momsoilc_demo_db', user: 'momsoilc_demo_u' },
      docRoot: 'public_html/demo',
      sslPending: false,
      cronSkipped: true,
      dryRun: false,
      callLog: [],
    },
  });
}

seedDemo();
