/**
 * Project store + provisioning job runner — Prisma (Neon Postgres) backed.
 *
 * Provisioning calls the REAL `createProject()` from @baas-195/adapter-cpanel.
 * Durable project ownership is established before any hosting mutation begins.
 */
import { randomBytes } from 'crypto';
import {
  createProject,
  deleteProject,
  UapiClient,
  ProvisionError,
} from '@baas-195/adapter-cpanel';
import type { ProjectProvisioned, UapiConfig } from '@baas-195/adapter-cpanel';
import { prisma } from './db';
import { getConnection, type HostingConnection } from './connection';
import { insecureFetch } from './tls';

export type StepState = 'pending' | 'running' | 'done' | 'failed' | 'skipped';

export interface ProjectStep {
  id: string;
  label: string;
  state: StepState;
  detail?: string;
  startedAt?: string;
  endedAt?: string;
}

export interface ProjectJob {
  id: string;
  name: string;
  domain: string;
  fqdn: string;
  port: number;
  status: 'provisioning' | 'ready' | 'failed';
  steps: ProjectStep[];
  result?: ProjectProvisioned;
  dbPassword?: string;
  error?: string;
  note?: string;
  seeded?: boolean;
  createdAt: string;
}

const activeJobs = new Map<string, ProjectJob>();

const STEP_DEFS: Array<{ id: string; label: string }> = [
  { id: 'subdomain', label: 'Create subdomain' },
  { id: 'database', label: 'Create MySQL database' },
  { id: 'dbuser', label: 'Create database user' },
  { id: 'privileges', label: 'Grant privileges' },
  { id: 'ssl', label: 'Issue SSL certificate (AutoSSL)' },
  { id: 'cron', label: 'Install watchdog cron' },
  { id: 'proxy', label: 'Write proxy rules (.htaccess)' },
];

function stepIdFor(module: string, func: string): string | null {
  if (module === 'SubDomain' && func === 'addsubdomain') return 'subdomain';
  if (module === 'Mysql' && func === 'create_database') return 'database';
  if (module === 'Mysql' && func === 'create_user') return 'dbuser';
  if (module === 'Mysql' && func === 'set_privileges_on_database') return 'privileges';
  if (module === 'SSL') return 'ssl';
  if (module === 'Cron') return 'cron';
  if (module === 'Fileman' && func === 'save_file_content') return 'proxy';
  return null;
}

function markStep(job: ProjectJob, id: string, state: StepState, detail?: string): void {
  const s = job.steps.find((x) => x.id === id);
  if (!s) return;
  s.state = state;
  if (detail) s.detail = detail;
  const now = new Date().toISOString();
  if (state === 'running' && !s.startedAt) s.startedAt = now;
  if (state === 'done' || state === 'failed' || state === 'skipped') s.endedAt = now;
  void persistJob(job).catch(() => {});
}

async function persistJob(job: ProjectJob): Promise<void> {
  await prisma.project.update({
    where: { id: job.id },
    data: {
      status: job.status,
      fqdn: job.fqdn,
      port: job.port,
      dbName: job.result?.db.name ?? null,
      dbUser: job.result?.db.user ?? null,
      steps: job.steps as unknown as object,
    },
  }).catch(() => {});
}

function trackingFetch(job: ProjectJob): typeof fetch {
  const base = insecureFetch as unknown as typeof fetch;
  return (async (input: string | URL | Request, init?: RequestInit) => {
    const raw = typeof input === 'string' ? input : input instanceof URL ? input.toString() : input.url;
    const m = raw.match(/\/execute\/(\w+)\/(\w+)/);
    const stepId = m ? stepIdFor(m[1], m[2]) : null;
    if (stepId) markStep(job, stepId, 'running');
    try {
      const res = await base(raw, init);
      if (stepId) markStep(job, stepId, 'done');
      return res;
    } catch (e) {
      if (stepId) {
        const s = job.steps.find((x) => x.id === stepId);
        if (s && s.state !== 'running') markStep(job, stepId, 'running', 'retrying…');
      }
      throw e;
    }
  }) as typeof fetch;
}

function htaccessFor(fqdn: string, port: number): string {
  const escaped = fqdn.replace(/\./g, '\\.');
  return [
    `# Generated by 1.95 BaaS control plane — ${fqdn} -> 127.0.0.1:${port}`,
    `# PocketBase API + admin UI proxied to the project binary; static files`,
    `# in the document root are served directly.`,
    `RewriteEngine On`,
    `RewriteCond %{HTTP_HOST} ^${escaped}$ [NC]`,
    `RewriteCond %{REQUEST_URI} ^/api/ [OR]`,
    `RewriteCond %{REQUEST_URI} ^/_/`,
    `RewriteRule ^(.*)$ http://127.0.0.1:${port}/$1 [P,L,QSA]`,
    ``,
  ].join('\n');
}

async function defaultUserId(): Promise<string> {
  const user = await prisma.user.upsert({
    where: { email: 'owner@local' },
    update: {},
    create: { email: 'owner@local', name: 'Owner' },
  });
  return user.id;
}

async function allocatePort(): Promise<number> {
  const used = new Set<number>();
  for (const j of activeJobs.values()) used.add(j.port);
  const rows = await prisma.project.findMany({ select: { port: true } });
  for (const r of rows) used.add(r.port);
  let port = 18001;
  while (used.has(port) && port < 18999) port++;
  if (port > 18999) throw new Error('port range 18001–18999 exhausted');
  return port;
}

function rowToJob(row: {
  id: string; name: string; domain: string; fqdn: string; port: number;
  status: string; steps: unknown; createdAt: Date;
}): ProjectJob {
  const steps = Array.isArray(row.steps)
    ? (row.steps as ProjectStep[])
    : STEP_DEFS.map((d) => ({
        ...d,
        state: (row.status === 'ready' ? 'done' : 'pending') as StepState,
      }));
  return {
    id: row.id,
    name: row.name,
    domain: row.domain,
    fqdn: row.fqdn,
    port: row.port,
    status: row.status as ProjectJob['status'],
    steps,
    createdAt: row.createdAt.toISOString(),
    ...(row.id === 'demo'
      ? {
          seeded: true,
          note: 'Live demo project provisioned 2026-10-06. Public URL is served via the vibecode subdomain until the host fixes new vhosts; PocketBase runs on 127.0.0.1:18001.',
        }
      : {}),
  };
}

export async function listJobs(): Promise<ProjectJob[]> {
  await ensureSeeded();
  const userId = await defaultUserId();
  const rows = await prisma.project.findMany({
    where: { userId },
    orderBy: { createdAt: 'desc' },
  });
  const byId = new Map(rows.map((r) => [r.id, rowToJob(r)]));
  for (const j of activeJobs.values()) byId.set(j.id, j);
  return [...byId.values()].sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

export async function getJob(id: string): Promise<ProjectJob | undefined> {
  const live = activeJobs.get(id);
  if (live) return live;
  const row = await prisma.project.findUnique({ where: { id } });
  return row ? rowToJob(row) : undefined;
}

/**
 * Provision only after the caller has authenticated the owner and selected the
 * exact hosting connection. The provisioner never resolves tenancy itself.
 */
export async function startProvisioningFor(
  userId: string,
  connection: HostingConnection,
  name: string,
  domain: string,
): Promise<ProjectJob> {
  const id = `${name}-${Date.now().toString(36)}`;
  const port = await allocatePort();
  const job: ProjectJob = {
    id,
    name,
    domain,
    fqdn: `${name}.${domain}`,
    port,
    status: 'provisioning',
    steps: STEP_DEFS.map((d) => ({ ...d, state: 'pending' as StepState })),
    createdAt: new Date().toISOString(),
  };

  await prisma.project.create({
    data: {
      id,
      userId,
      connectionId: connection.id,
      name,
      domain,
      fqdn: job.fqdn,
      port,
      status: 'provisioning',
      steps: job.steps as unknown as object,
    },
  });

  activeJobs.set(id, job);
  void runProvisioning(id, connection);
  return job;
}

/** Backward-compatible platform-owner entry point used only by legacy/demo code. */
export async function startProvisioning(name: string, domain: string): Promise<ProjectJob> {
  const conn = await getConnection();
  if (!conn) throw new Error('No hosting connection. Connect hosting first.');
  const userId = await defaultUserId();
  return startProvisioningFor(userId, conn, name, domain);
}

async function runProvisioning(id: string, conn: HostingConnection): Promise<void> {
  const job = activeJobs.get(id);
  if (!job) return;
  const dbPassword = randomBytes(18).toString('base64').replace(/[^A-Za-z0-9]/g, 'x');
  job.dbPassword = dbPassword;

  const cfg: UapiConfig = {
    host: conn.host,
    user: conn.user,
    apiToken: conn.apiToken,
    fetchImpl: trackingFetch(job),
  };

  try {
    const provisioned = await createProject(cfg, {
      name: job.name,
      domain: job.domain,
      port: job.port,
      dbPassword,
      sslTimeoutMs: 60_000,
    });

    try {
      const client = new UapiClient({ ...cfg, fetchImpl: trackingFetch(job) });
      await client.writeFile(provisioned.docRoot, '.htaccess', htaccessFor(provisioned.fqdn, provisioned.port));
    } catch (e) {
      markStep(job, 'proxy', 'failed', `proxy rules not written: ${(e as Error).message} — place .htaccess manually`);
    }

    job.result = provisioned;
    job.status = 'ready';
    for (const s of job.steps) if (s.state === 'pending') markStep(job, s.id, 'skipped', 'not needed');
  } catch (e) {
    const msg =
      e instanceof ProvisionError
        ? `Failed at step "${e.step}": ${e.cause}`
        : (e as Error).message;
    for (const s of job.steps) if (s.state === 'running') markStep(job, s.id, 'failed');
    job.status = 'failed';
    job.error = msg;
  } finally {
    await persistJob(job);
    if (job.status !== 'provisioning') activeJobs.delete(id);
  }
}

export async function teardownProjectWithConnection(
  id: string,
  conn: HostingConnection,
): Promise<{ removed: string[]; errors: Array<{ step: string; error: string }> }> {
  const job = await getJob(id);
  if (!job) throw new Error('unknown project');
  const report = await deleteProject(
    { host: conn.host, user: conn.user, apiToken: conn.apiToken, fetchImpl: insecureFetch as unknown as typeof fetch },
    { name: job.name, domain: job.domain },
  );
  activeJobs.delete(id);
  await prisma.project.deleteMany({ where: { id } });
  return { removed: report.removed, errors: report.errors };
}

/** Backward-compatible platform-owner teardown entry point. */
export async function teardownProject(id: string): Promise<{ removed: string[]; errors: Array<{ step: string; error: string }> }> {
  const conn = await getConnection();
  if (!conn) throw new Error('No hosting connection.');
  return teardownProjectWithConnection(id, conn);
}

async function ensureSeeded(): Promise<void> {
  const userId = await defaultUserId();
  const existing = await prisma.project.findUnique({ where: { id: 'demo' } });
  if (existing) return;
  const done: ProjectStep[] = STEP_DEFS.map((d) => ({
    ...d,
    state: 'done' as StepState,
    startedAt: '2026-10-06T04:15:00Z',
    endedAt: '2026-10-06T04:29:00Z',
  }));
  await prisma.project.create({
    data: {
      id: 'demo',
      userId,
      name: 'demo',
      domain: 'momsoilchange.com',
      fqdn: 'vibecode.momsoilchange.com',
      port: 18001,
      dbName: 'momsoilc_demo_db',
      dbUser: 'momsoilc_demo_u',
      status: 'ready',
      steps: done as unknown as object,
    },
  });
}
