import Foundation
import Security

public struct InvisibleDBError:Error,LocalizedError{public let status:Int;public let message:String;public var errorDescription:String?{"InvisibleDB \(status): \(message)"}}
public struct ListOptions{public var page:Int?;public var perPage:Int?;public var sort:String?;public var filter:String?;public var expand:String?;public init(page:Int?=nil,perPage:Int?=nil,sort:String?=nil,filter:String?=nil,expand:String?=nil){self.page=page;self.perPage=perPage;self.sort=sort;self.filter=filter;self.expand=expand}}
public struct UploadPart{public let field:String;public let filename:String;public let mimeType:String;public let data:Data;public init(field:String,filename:String,mimeType:String,data:Data){self.field=field;self.filename=filename;self.mimeType=mimeType;self.data=data}}
public protocol InvisibleDBTokenStore{func load()throws->String?;func save(_ token:String)throws;func clear()throws}
public final class KeychainTokenStore:InvisibleDBTokenStore{private let service:String;private let account:String;public init(service:String="app.invisibledb.sdk",account:String="session"){self.service=service;self.account=account}
 public func load()throws->String?{let q:[String:Any]=[kSecClass as String:kSecClassGenericPassword,kSecAttrService as String:service,kSecAttrAccount as String:account,kSecReturnData as String:true,kSecMatchLimit as String:kSecMatchLimitOne];var r:AnyObject?;let s=SecItemCopyMatching(q as CFDictionary,&r);if s==errSecItemNotFound{return nil};guard s==errSecSuccess,let d=r as? Data else{throw InvisibleDBError(status:Int(s),message:"keychain read failed")};return String(data:d,encoding:.utf8)}
 public func save(_ token:String)throws{try clear();let q:[String:Any]=[kSecClass as String:kSecClassGenericPassword,kSecAttrService as String:service,kSecAttrAccount as String:account,kSecValueData as String:Data(token.utf8),kSecAttrAccessible as String:kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly];let s=SecItemAdd(q as CFDictionary,nil);guard s==errSecSuccess else{throw InvisibleDBError(status:Int(s),message:"keychain write failed")}}
 public func clear()throws{let q:[String:Any]=[kSecClass as String:kSecClassGenericPassword,kSecAttrService as String:service,kSecAttrAccount as String:account];let s=SecItemDelete(q as CFDictionary);guard s==errSecSuccess||s==errSecItemNotFound else{throw InvisibleDBError(status:Int(s),message:"keychain clear failed")}}}

public final class InvisibleDB{
 public let baseUrl:String;private let apiKey:String?;private let tokenStore:InvisibleDBTokenStore;private let session:URLSession;private let retries:Int;private let lock=NSLock();private var token:String?
 public init(baseUrl:String,apiKey:String?=nil,tokenStore:InvisibleDBTokenStore=KeychainTokenStore(),timeout:TimeInterval=15,retries:Int=2){self.baseUrl=baseUrl.trimmingCharacters(in:CharacterSet(charactersIn:"/"));self.apiKey=apiKey;self.tokenStore=tokenStore;self.retries=retries;let c=URLSessionConfiguration.default;c.timeoutIntervalForRequest=timeout;c.timeoutIntervalForResource=timeout*2;self.session=URLSession(configuration:c);self.token=try? tokenStore.load()}
 public var isAuthenticated:Bool{lock.withLock{token != nil}||apiKey != nil}
 private func credential()->String?{if let t=lock.withLock({token}){return t};if let t=try? tokenStore.load(){if let t{lock.withLock{token=t};return t}};return apiKey}
 fileprivate func request(_ method:String,_ path:String,body:Data?=nil,contentType:String?="application/json",query:[String:String]=[:],authRequired:Bool=true)async throws->Any{var comps=URLComponents(string:baseUrl+path)!;if !query.isEmpty{comps.queryItems=query.map{URLQueryItem(name:$0.key,value:$0.value)}};var last:Error?
  for attempt in 0...retries{var req=URLRequest(url:comps.url!);req.httpMethod=method;if let c=credential(){req.setValue("Bearer \(c)",forHTTPHeaderField:"Authorization")}else if authRequired{throw InvisibleDBError(status:401,message:"authentication required")};if let contentType{req.setValue(contentType,forHTTPHeaderField:"Content-Type")};req.httpBody=body
   do{let(data,res)=try await session.data(for:req);let status=(res as? HTTPURLResponse)?.statusCode ?? 0;if status==401{throw InvisibleDBError(status:401,message:"invalid credentials")};if !(200..<300).contains(status){let text=String(data:data,encoding:.utf8).map{String($0.prefix(300))} ?? "request failed";if(status==429||status>=500)&&attempt<retries{try await Task.sleep(nanoseconds:UInt64(250_000_000*(1<<attempt)));continue};throw InvisibleDBError(status:status,message:text)};if status==204||data.isEmpty{return NSNull()};return try JSONSerialization.jsonObject(with:data)}catch{last=error;if error is InvisibleDBError{throw error};if attempt>=retries{throw error};try await Task.sleep(nanoseconds:UInt64(250_000_000*(1<<attempt)))}}
  throw last ?? InvisibleDBError(status:0,message:"request failed")}
 @discardableResult public func authWithPassword(collection:String,identity:String,password:String)async throws->[String:Any]{let b=try JSONSerialization.data(withJSONObject:["identity":identity,"password":password]);guard let r=try await request("POST","/api/collections/\(collection)/auth-with-password",body:b,authRequired:false) as? [String:Any],let t=r["token"] as? String else{throw InvisibleDBError(status:500,message:"auth response missing token")};lock.withLock{token=t};try tokenStore.save(t);return r}
 public func logout()throws{lock.withLock{token=nil};try tokenStore.clear()};public func collection(_ name:String)->Collection{Collection(db:self,name:name)};public func fileUrl(collection:String,recordId:String,filename:String)->String{"\(baseUrl)/api/files/\(collection)/\(recordId)/\(filename)"}
 public func vectorQuery(collection:String,embedding:[Double],limit:Int=10)async throws->[[String:Any]]{let b=try JSONSerialization.data(withJSONObject:["collection":collection,"embedding":embedding,"limit":limit]);let r=try await request("POST","/api/vector/query",body:b) as! [String:Any];return r["results"] as? [[String:Any]] ?? []};public func health()async throws->[String:Any]{try await request("GET","/api/health") as! [String:Any]}
 fileprivate func upload(_ method:String,path:String,fields:[String:Any],files:[UploadPart])async throws->[String:Any]{let boundary="InvisibleDB-\(UUID().uuidString)";var d=Data();for(k,v)in fields{d.append("--\(boundary)\r\nContent-Disposition: form-data; name=\"\(k)\"\r\n\r\n\(v)\r\n".data(using:.utf8)!)};for f in files{d.append("--\(boundary)\r\nContent-Disposition: form-data; name=\"\(f.field)\"; filename=\"\(f.filename)\"\r\nContent-Type: \(f.mimeType)\r\n\r\n".data(using:.utf8)!);d.append(f.data);d.append("\r\n".data(using:.utf8)!)};d.append("--\(boundary)--\r\n".data(using:.utf8)!);return try await request(method,path,body:d,contentType:"multipart/form-data; boundary=\(boundary)") as! [String:Any]}
 public func subscribe(collection:String,onEvent:@escaping([String:Any])->Void)async throws->RealtimeSubscription{let h=try await request("POST","/api/realtime",body:Data()) as! [String:Any];guard let id=h["clientId"] as? String else{throw InvisibleDBError(status:500,message:"realtime handshake missing clientId")};let b=try JSONSerialization.data(withJSONObject:["clientId":id,"subscriptions":[collection]]);_=try await request("POST","/api/realtime",body:b);var req=URLRequest(url:URL(string:"\(baseUrl)/api/realtime?clientId=\(id)")!);if let c=credential(){req.setValue("Bearer \(c)",forHTTPHeaderField:"Authorization")}else{throw InvisibleDBError(status:401,message:"authentication required")};let t=Task{let(bytes,_)=try await session.bytes(for:req);for try await line in bytes.lines{guard line.hasPrefix("data:") else{continue};let p=line.dropFirst(5).trimmingCharacters(in:.whitespaces);guard let d=p.data(using:.utf8),let o=try? JSONSerialization.jsonObject(with:d) as? [String:Any] else{continue};onEvent(o)}};return RealtimeSubscription(task:t)}
}
public final class RealtimeSubscription{private let task:Task<Void,Error>;fileprivate init(task:Task<Void,Error>){self.task=task};public func cancel(){task.cancel()};deinit{task.cancel()}}
public final class Collection{private let db:InvisibleDB;public let name:String;private var path:String{"/api/collections/\(name)/records"};fileprivate init(db:InvisibleDB,name:String){self.db=db;self.name=name}
 public func getList(_ o:ListOptions=ListOptions())async throws->[String:Any]{var q:[String:String]=[:];if let v=o.page{q["page"]=String(v)};if let v=o.perPage{q["perPage"]=String(v)};if let v=o.sort{q["sort"]=v};if let v=o.filter{q["filter"]=v};if let v=o.expand{q["expand"]=v};return try await db.request("GET",path,query:q) as! [String:Any]};public func getOne(_ id:String)async throws->[String:Any]{try await db.request("GET","\(path)/\(id)") as! [String:Any]};public func create(_ d:[String:Any])async throws->[String:Any]{try await db.request("POST",path,body:JSONSerialization.data(withJSONObject:d)) as! [String:Any]};public func update(_ id:String,_ d:[String:Any])async throws->[String:Any]{try await db.request("PATCH","\(path)/\(id)",body:JSONSerialization.data(withJSONObject:d)) as! [String:Any]};public func delete(_ id:String)async throws{_=try await db.request("DELETE","\(path)/\(id)")};public func createWithFiles(_ d:[String:Any],files:[UploadPart])async throws->[String:Any]{try await db.upload("POST",path:path,fields:d,files:files)};public func updateWithFiles(_ id:String,_ d:[String:Any],files:[UploadPart])async throws->[String:Any]{try await db.upload("PATCH",path:"\(path)/\(id)",fields:d,files:files)};public func subscribe(_ cb:@escaping([String:Any])->Void)async throws->RealtimeSubscription{try await db.subscribe(collection:name,onEvent:cb)}}
private extension NSLock{func withLock<T>(_ body:()throws->T)rethrows->T{lock();defer{unlock()};return try body()}}
